resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      categoryService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 2
        waitDurationInOpenState: 1s
        slidingWindowType: COUNT_BASED

  bulkhead:
    instances:
      categoryService:
        maxConcurrentCalls: 25
        maxWaitDuration: 0

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always